%define  debug_package %{nil}
Name: docker-proxy
Version: 0.8.0.dev.2
Release: 100
Summary: Proxy used for docker port mapping

License: Apache License 2.0
URL: https://github.com/docker/libnetwork
Source: %{name}.tar.gz

BuildRequires: golang >= 1.8.3
BuildRequires: make

%description


%prep
%setup -c -n libnetwork


%build
cwd=`pwd`
tar -xzvf libnetwork-d00ceed.tar.gz --strip-components 1
export CGO_ENABLED=0
export GOPATH=`pwd`/.gopath
mkdir -p $GOPATH/src/github.com/docker/
ln -sfn `pwd` $GOPATH/src/github.com/docker/libnetwork
cd $GOPATH/src/github.com/docker/libnetwork
go build -buildmode=pie -ldflags="-linkmode=external -s -w -buildid=IdByIsula -extldflags=-zrelro -extldflags=-znow " -o docker-proxy ./cmd/proxy
cd $cwd


%install
install -d $RPM_BUILD_ROOT/%{_bindir}
install -p -m 755 docker-proxy $RPM_BUILD_ROOT/%{_bindir}/docker-proxy


%clean
%{__rm} -rf %{_bindir}/docker-proxy


%files
%{_bindir}/docker-proxy


%changelog
* Sat Aug 19 2019 songnannan<songnannan2@huawei.com> 0.8.0.dev.2-2.h1
- Type:bugfix
- Id:NA
- SUG:NA
- DESC:the debuginfo and debugsource packages are not generated by default
